#ifndef UCONTEXT_OFFSETS_H
#define UCONTEXT_OFFSETS_H

#define MCONTEXT_ARM_R0 32
#define MCONTEXT_ARM_R4 48
#define MCONTEXT_ARM_SP 84
#define MCONTEXT_ARM_LR 88
#define MCONTEXT_ARM_PC 92
#define UCONTEXT_REGSPACE 232

#endif
